services:
  - type: web
    name: mangatheque
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mangatheque-db
          property: connectionString
      - key: MESSENGER_TRANSPORT_DSN
        value: "doctrine://default"
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction --no-ansi
      composer run-script render-build

databases:
  - name: mangatheque-db
    databaseName: mangatheque
    user: mangatheque 